### ISSUE TITLE
Angular 16

### ISSUE THREAD

**Issue by certifirm** [Alorel/ngx-sails#242]
Please, update to Angular 16.

Thanks

**Comment by Prasannajaga** [comment]
Hey bro I didn't find any angular app in this repo.

**Comment by Alorel** [comment]
Most likely getting this published tomorrow, the automatic release script is struggling

**Comment by Prasannajaga** [comment]
sorry I don't know abt .yml files.

**Comment by certifirm** [comment]
Thanks a lot.
